# Generated by Django 4.0.2 on 2022-02-11 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_sequence', models.CharField(max_length=5001)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='userApp.organization')),
            ],
        ),
    ]
