# Generated by Django 4.0.2 on 2022-02-11 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.09, max_digits=6)),
                ('payment_status', models.CharField(choices=[('R', 'Under Review'), ('P', 'In Production')], default='R', max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='store.dna')),
            ],
        ),
    ]
